services:
  - type: web
    name: agroverse-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You'll set this in Render dashboard
      - key: JWT_SECRET
        sync: false # You'll set this in Render dashboard